$mainMod = SUPER

bind = $mainMod, Q, exec, alacritty
bind = $mainMod, M, exit,
bind = $mainMod, C, killactive,

input {
    kb_layout = br
    kb_variant = abnt2
}
exe-once = alacritty

# Garuda Tools (menus forense e produtividade)
source = ~/.config/hypr/garuda-tools.conf
source = ~/.config/hypr/garuda-floating.conf
